// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkfoekamzxvrwnchmsvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrZm9la2Ftenh2cnduY2htc3Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTY1MzYsImV4cCI6MjA2MzU5MjUzNn0.FVi4IB9FwbKib36pnv-Q-s6zDSSR6M9fNiHMkcwboIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);